// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public static class NanosUtils
{
    public static bool IsA(ILuaVM vm, object object, object type)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "NanosUtils");
        vm.GetField(-1, "IsA");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, object);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, type);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsEntityValid(ILuaVM vm, object entity)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "NanosUtils");
        vm.GetField(-1, "IsEntityValid");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, entity);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static string Dump(ILuaVM vm, Dictionary<string, object> table)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "NanosUtils");
        vm.GetField(-1, "Dump");
        pc++;
        vm.MCall(pc, 1);
        var r0 = vm.ToString(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static void Benchmark(ILuaVM vm, string name, double amount, int func, params object[] args)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "NanosUtils");
        vm.GetField(-1, "Benchmark");
        pc++;
        vm.PushString(name);
        pc++;
        vm.PushNumber(amount);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, func);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, args);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static string FormatString(ILuaVM vm, string text, params object[] args)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "NanosUtils");
        vm.GetField(-1, "FormatString");
        pc++;
        vm.PushString(text);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, args);
        vm.MCall(pc, 1);
        var r0 = vm.ToString(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

}

