// Autogenerated by the NanosSharp Server Bindings Generator (c) 2025 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public static class BChat
{
    public static void SendMessage(ILuaVM vm, LuaRef player, string message)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Chat");
        vm.GetField(-1, "SendMessage");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, player);
        pc++;
        vm.PushString(message);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void BroadcastMessage(ILuaVM vm, string message)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Chat");
        vm.GetField(-1, "BroadcastMessage");
        pc++;
        vm.PushString(message);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

}

