// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public static class HTTP
{
    public static void Request(ILuaVM vm, string uri, string? endpoint = null, string? method = null, string? data = null, string? content_type = null, bool? compress = null, Dictionary<string, object>? headers = null, int? callback = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "HTTP");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Request");
        pc++;
        vm.PushString(uri);
        if (endpoint != null)
        {
             pc++;
             vm.PushString(endpoint);
        }
        if (method != null)
        {
             pc++;
             vm.PushString(method);
        }
        if (data != null)
        {
             pc++;
             vm.PushString(data);
        }
        if (content_type != null)
        {
             pc++;
             vm.PushString(content_type);
        }
        if (compress != null)
        {
             pc++;
             vm.PushBoolean(compress.Value);
        }
        if (headers != null)
        {
             pc++;
        }
        if (callback != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, callback.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public struct RequestSync_Return0
    {
        public double Status;
        public string Data;
    }

    public static RequestSync_Return0 RequestSync(ILuaVM vm, string uri, string? endpoint = null, string? method = null, string? data = null, string? content_type = null, bool? compress = null, Dictionary<string, object>? headers = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "HTTP");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "RequestSync");
        pc++;
        vm.PushString(uri);
        if (endpoint != null)
        {
             pc++;
             vm.PushString(endpoint);
        }
        if (method != null)
        {
             pc++;
             vm.PushString(method);
        }
        if (data != null)
        {
             pc++;
             vm.PushString(data);
        }
        if (content_type != null)
        {
             pc++;
             vm.PushString(content_type);
        }
        if (compress != null)
        {
             pc++;
             vm.PushBoolean(compress.Value);
        }
        if (headers != null)
        {
             pc++;
        }
        vm.MCall(pc, 1);
        vm.ClearStack();
        return r0;
    }

}

