// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class Actor
{
    public static void AddImpulse(ILuaVM vm, LuaRef selfRef, LuaRef force, bool? velocity_change = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "AddImpulse");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, force);
        if (velocity_change != null)
        {
             pc++;
             vm.PushBoolean(velocity_change.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void AttachTo(ILuaVM vm, LuaRef selfRef, LuaRef other, AttachmentRule? attachment_rule = null, string? bone_name = null, LuaRef? lifespan_when_detached = null, bool? use_absolute_rotation = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "AttachTo");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, other);
        if (attachment_rule != null)
        {
             pc++;
             vm.PushEnum(attachment_rule.Value);
        }
        if (bone_name != null)
        {
             pc++;
             vm.PushString(bone_name);
        }
        if (lifespan_when_detached != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, lifespan_when_detached.Value);
        }
        if (use_absolute_rotation != null)
        {
             pc++;
             vm.PushBoolean(use_absolute_rotation.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void Detach(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Detach");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetCollision(ILuaVM vm, LuaRef selfRef, CollisionType collision_type)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetCollision");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushEnum(collision_type);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetDimension(ILuaVM vm, LuaRef selfRef, LuaRef dimension)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetDimension");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, dimension);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetForce(ILuaVM vm, LuaRef selfRef, LuaRef force, bool? is_local = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetForce");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, force);
        if (is_local != null)
        {
             pc++;
             vm.PushBoolean(is_local.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetGravityEnabled(ILuaVM vm, LuaRef selfRef, bool gravity_enabled)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetGravityEnabled");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushBoolean(gravity_enabled);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetVisibility(ILuaVM vm, LuaRef selfRef, bool is_visible)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetVisibility");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushBoolean(is_visible);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetLifeSpan(ILuaVM vm, LuaRef selfRef, LuaRef seconds)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetLifeSpan");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, seconds);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetLocation(ILuaVM vm, LuaRef selfRef, LuaRef location)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetLocation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, location);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetRotation(ILuaVM vm, LuaRef selfRef, LuaRef rotation)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetRotation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, rotation);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetRelativeLocation(ILuaVM vm, LuaRef selfRef, LuaRef relative_location)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetRelativeLocation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, relative_location);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetRelativeRotation(ILuaVM vm, LuaRef selfRef, LuaRef relative_rotation)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetRelativeRotation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, relative_rotation);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetScale(ILuaVM vm, LuaRef selfRef, LuaRef scale)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetScale");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, scale);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetNetworkAuthority(ILuaVM vm, LuaRef selfRef, LuaRef? player = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetNetworkAuthority");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        if (player != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, player.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetNetworkAuthorityAutoDistributed(ILuaVM vm, LuaRef selfRef, bool auto_distribute)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetNetworkAuthorityAutoDistributed");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushBoolean(auto_distribute);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void TranslateTo(ILuaVM vm, LuaRef selfRef, LuaRef location, LuaRef time, LuaRef? exp = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "TranslateTo");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, location);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, time);
        if (exp != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, exp.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void RotateTo(ILuaVM vm, LuaRef selfRef, LuaRef rotation, LuaRef time, LuaRef? exp = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "RotateTo");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, rotation);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, time);
        if (exp != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, exp.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static bool IsBeingDestroyed(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsBeingDestroyed");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsVisible(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsVisible");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsGravityEnabled(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsGravityEnabled");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsInWater(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsInWater");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsNetworkDistributed(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsNetworkDistributed");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static LuaRef[] GetAttachedEntities(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetAttachedEntities");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToRefArray(-1);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef? GetAttachedTo(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetAttachedTo");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static CollisionType GetCollision(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetCollision");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToEnum<CollisionType>(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetLocation(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetLocation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetRelativeLocation(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetRelativeLocation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef? GetNetworkAuthority(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetNetworkAuthority");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetRotation(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetRotation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetRelativeRotation(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetRelativeRotation");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetForce(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetForce");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetDimension(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetDimension");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetScale(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetScale");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static LuaRef GetVelocity(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Actor");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetVelocity");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

}

