// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class Blueprint : Paintable
{
    public static object CallBlueprintEvent(ILuaVM vm, int selfRef, string event_name, params object[] arguments)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Blueprint");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "CallBlueprintEvent");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(event_name);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, arguments);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

}

