// Autogenerated by the NanosSharp Server Bindings Generator (c) 2025 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class BBlueprint : BEntity
{
    public static LuaRef CallBlueprintEvent(ILuaVM vm, LuaRef selfRef, string event_name, params object[] arguments)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Blueprint");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "CallBlueprintEvent");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(event_name);
        foreach (var a in arguments) {
            pc++;
            vm.PushObject(a);
        }
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

}

