// Autogenerated by the NanosSharp Server Bindings Generator (c) 2025 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class BFile
{
    public static void Close(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Close");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void Flush(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Flush");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static bool IsEOF(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsEOF");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsBad(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsBad");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsGood(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "IsGood");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool HasFailed(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "HasFailed");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static string Read(ILuaVM vm, LuaRef selfRef, long? length = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Read");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        if (length != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, length.Value);
        }
        vm.MCall(pc, 1);
        var r0 = vm.ToString(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static void ReadAsync(ILuaVM vm, LuaRef selfRef, long length, ILuaVM.CFunction callback)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "ReadAsync");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, length);
        pc++;
        vm.PushManagedFunction(callback);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static string ReadLine(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "ReadLine");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToString(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static Dictionary<string, object> ReadJSON(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "ReadJSON");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToTable(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static void ReadJSONAsync(ILuaVM vm, LuaRef selfRef, ILuaVM.CFunction callback)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "ReadJSONAsync");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushManagedFunction(callback);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void Seek(ILuaVM vm, LuaRef selfRef, long position)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Seek");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, position);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static long Size(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Size");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static void Skip(ILuaVM vm, LuaRef selfRef, long amount)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Skip");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, amount);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static long Tell(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Tell");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static void Write(ILuaVM vm, LuaRef selfRef, string data)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Write");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(data);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static long Time(ILuaVM vm, string path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "Time");
        pc++;
        vm.PushString(path);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static bool CreateDirectory(ILuaVM vm, string path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "CreateDirectory");
        pc++;
        vm.PushString(path);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static long Remove(ILuaVM vm, string path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "Remove");
        pc++;
        vm.PushString(path);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static bool Exists(ILuaVM vm, string path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "Exists");
        pc++;
        vm.PushString(path);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsDirectory(ILuaVM vm, string path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "IsDirectory");
        pc++;
        vm.PushString(path);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static bool IsRegularFile(ILuaVM vm, string path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "IsRegularFile");
        pc++;
        vm.PushString(path);
        vm.MCall(pc, 1);
        var r0 = vm.ToBoolean(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static string[] GetDirectories(ILuaVM vm, string? path_filter = null, long? max_depth = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "GetDirectories");
        if (path_filter != null)
        {
             pc++;
             vm.PushString(path_filter);
        }
        if (max_depth != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, max_depth.Value);
        }
        vm.MCall(pc, 1);
        var r0 = vm.ToArray<string>(-1);
        vm.ClearStack();
        return r0;
    }

    public static string[] GetFiles(ILuaVM vm, string? path_filter = null, string? extension_filter = null, long? max_depth = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "GetFiles");
        if (path_filter != null)
        {
             pc++;
             vm.PushString(path_filter);
        }
        if (extension_filter != null)
        {
             pc++;
             vm.PushString(extension_filter);
        }
        if (max_depth != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, max_depth.Value);
        }
        vm.MCall(pc, 1);
        var r0 = vm.ToArray<string>(-1);
        vm.ClearStack();
        return r0;
    }

    public static string GetFullPath(ILuaVM vm, string path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "File");
        vm.GetField(-1, "GetFullPath");
        pc++;
        vm.PushString(path);
        vm.MCall(pc, 1);
        var r0 = vm.ToString(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

}

