// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class Grenade : Pickable
{
    public static void Explode(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "Explode");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetDamage(ILuaVM vm, int selfRef, double? base_damage = null, double? minimum_damage = null, double? damage_inner_radius = null, double? damage_outer_radius = null, double? damage_falloff = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetDamage");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        if (base_damage != null)
        {
             pc++;
             vm.PushNumber(base_damage.Value);
        }
        if (minimum_damage != null)
        {
             pc++;
             vm.PushNumber(minimum_damage.Value);
        }
        if (damage_inner_radius != null)
        {
             pc++;
             vm.PushNumber(damage_inner_radius.Value);
        }
        if (damage_outer_radius != null)
        {
             pc++;
             vm.PushNumber(damage_outer_radius.Value);
        }
        if (damage_falloff != null)
        {
             pc++;
             vm.PushNumber(damage_falloff.Value);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetTimeToExplode(ILuaVM vm, int selfRef, double time)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetTimeToExplode");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushNumber(time);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetThrowForce(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetThrowForce");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static double GetBaseDamage(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetBaseDamage");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToNumber(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static double GetDamageFalloff(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetDamageFalloff");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToNumber(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static double GetDamageInnerRadius(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetDamageInnerRadius");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToNumber(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static double GetDamageOuterRadius(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetDamageOuterRadius");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToNumber(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static double GetMinimumDamage(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetMinimumDamage");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToNumber(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static double GetTimeToExplode(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetTimeToExplode");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToNumber(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static double GetThrowForce(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Grenade");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetThrowForce");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToNumber(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

}

