// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class Paintable
{
    public static void SetMaterial(ILuaVM vm, LuaRef selfRef, string material_path, LuaRef? index = null, string? attachable_id = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Paintable");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetMaterial");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(material_path);
        if (index != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, index.Value);
        }
        if (attachable_id != null)
        {
             pc++;
             vm.PushString(attachable_id);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void ResetMaterial(ILuaVM vm, LuaRef selfRef, LuaRef? index = null, string? attachable_id = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Paintable");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "ResetMaterial");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        if (index != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, index.Value);
        }
        if (attachable_id != null)
        {
             pc++;
             vm.PushString(attachable_id);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetMaterialColorParameter(ILuaVM vm, LuaRef selfRef, string parameter_name, LuaRef color, LuaRef? index = null, string? attachable_id = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Paintable");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetMaterialColorParameter");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(parameter_name);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, color);
        if (index != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, index.Value);
        }
        if (attachable_id != null)
        {
             pc++;
             vm.PushString(attachable_id);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetMaterialScalarParameter(ILuaVM vm, LuaRef selfRef, string parameter_name, LuaRef scalar, LuaRef? index = null, string? attachable_id = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Paintable");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetMaterialScalarParameter");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(parameter_name);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, scalar);
        if (index != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, index.Value);
        }
        if (attachable_id != null)
        {
             pc++;
             vm.PushString(attachable_id);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetMaterialTextureParameter(ILuaVM vm, LuaRef selfRef, string parameter_name, string texture_path, LuaRef? index = null, string? attachable_id = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Paintable");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetMaterialTextureParameter");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(parameter_name);
        pc++;
        vm.PushString(texture_path);
        if (index != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, index.Value);
        }
        if (attachable_id != null)
        {
             pc++;
             vm.PushString(attachable_id);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetMaterialVectorParameter(ILuaVM vm, LuaRef selfRef, string parameter_name, LuaRef vector, LuaRef? index = null, string? attachable_id = null)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Paintable");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetMaterialVectorParameter");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(parameter_name);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, vector);
        if (index != null)
        {
             pc++;
             vm.RawGetI(ILuaVM.RegistryIndex, index.Value);
        }
        if (attachable_id != null)
        {
             pc++;
             vm.PushString(attachable_id);
        }
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetPhysicalMaterial(ILuaVM vm, LuaRef selfRef, string physical_material_path)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Paintable");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetPhysicalMaterial");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(physical_material_path);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

}

