// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class Prop : Paintable
{
    public static void SetGrabMode(ILuaVM vm, LuaRef selfRef, GrabMode grab_mode)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Prop");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetGrabMode");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushEnum(grab_mode);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetPhysicsDamping(ILuaVM vm, LuaRef selfRef, LuaRef linear_damping, LuaRef angular_damping)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Prop");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetPhysicsDamping");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, linear_damping);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, angular_damping);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetMesh(ILuaVM vm, LuaRef selfRef, string asset)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Prop");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetMesh");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.PushString(asset);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static string GetMesh(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Prop");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetMesh");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToString(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

    public static LuaRef? GetHandler(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Prop");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetHandler");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.Ref(ILuaVM.RegistryIndex);
        vm.ClearStack();
        return r0;
    }

    public static GrabMode GetGrabMode(ILuaVM vm, LuaRef selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Prop");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "GetGrabMode");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 1);
        var r0 = vm.ToEnum<GrabMode>(-1);
        vm.Pop();
        vm.ClearStack();
        return r0;
    }

}

