// Autogenerated by the NanosSharp Server Bindings Generator (c) 2022 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class Trigger : Actor
{
    public static void ForceOverlapChecking(ILuaVM vm, int selfRef)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Trigger");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "ForceOverlapChecking");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetExtent(ILuaVM vm, int selfRef, LuaRef extent)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "Trigger");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetExtent");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, extent);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

}

