// Autogenerated by the NanosSharp Server Bindings Generator (c) 2025 DasDarki / GPLv3

using NanosSharp.API;

namespace NanosSharp.Server.Bindings;

public class BVehicleWater : BEntity
{
    public static void SetEngineOffset(ILuaVM vm, LuaRef selfRef, LuaRef offset)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "VehicleWater");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetEngineOffset");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, offset);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

    public static void SetThrustStrength(ILuaVM vm, LuaRef selfRef, long force)
    {
        int pc = 0;
        vm.PushGlobalTable();
        vm.GetField(-1, "VehicleWater");
        vm.GetField(-1, "__function");
        vm.GetField(-1, "SetThrustStrength");
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, selfRef);
        pc++;
        vm.RawGetI(ILuaVM.RegistryIndex, force);
        vm.MCall(pc, 0);
        vm.ClearStack();
    }

}

